'use strict';

/**
 * The platform's place list (SPEC §12.1): `geo_regions`, seeded by
 * migration 181. Two levels:
 *
 *   governorate  Egypt's 27 governorates, plus "North Coast" (the summer
 *                coast from Sidi Kerir to Ras El Hekma, which merchants
 *                price on its own), and Saudi Arabia's 13 regions
 *   city         the cities and districts orders are delivered to
 *
 * Codes are global and never change once shipped: an Egyptian governorate
 * keeps the code already stored in shipping_governorate_rates and by the
 * storefront form (shipping/governorates.js), North Coast is `north-coast`,
 * a Saudi region is `sa-<name>`, and a city is `<parent>.<slug>`.
 *
 * Each entry below is [slug, Arabic name, English name]. A later change to
 * this list ships as a new migration; 403 inserts what is here once.
 */

const EGYPT = [
  ['cairo', 'القاهرة', 'Cairo', [
    ['nasr-city', 'مدينة نصر', 'Nasr City'],
    ['heliopolis', 'مصر الجديدة', 'Heliopolis'],
    ['new-cairo', 'القاهرة الجديدة', 'New Cairo'],
    ['fifth-settlement', 'التجمع الخامس', 'Fifth Settlement'],
    ['first-settlement', 'التجمع الأول', 'First Settlement'],
    ['rehab', 'مدينة الرحاب', 'Rehab City'],
    ['madinaty', 'مدينتي', 'Madinaty'],
    ['shorouk', 'مدينة الشروق', 'Shorouk City'],
    ['badr', 'مدينة بدر', 'Badr City'],
    ['new-capital', 'العاصمة الإدارية الجديدة', 'New Administrative Capital'],
    ['mostakbal-city', 'مدينة المستقبل', 'Mostakbal City'],
    ['katameya', 'القطامية', 'Katameya'],
    ['maadi', 'المعادي', 'Maadi'],
    ['zahraa-el-maadi', 'زهراء المعادي', 'Zahraa El Maadi'],
    ['mokattam', 'المقطم', 'Mokattam'],
    ['helwan', 'حلوان', 'Helwan'],
    ['15-may', 'مدينة 15 مايو', '15th of May City'],
    ['tebbin', 'التبين', 'Tebbin'],
    ['downtown', 'وسط البلد', 'Downtown'],
    ['zamalek', 'الزمالك', 'Zamalek'],
    ['garden-city', 'جاردن سيتي', 'Garden City'],
    ['manial', 'المنيل', 'Manial'],
    ['abdeen', 'عابدين', 'Abdeen'],
    ['sayeda-zeinab', 'السيدة زينب', 'Sayeda Zeinab'],
    ['old-cairo', 'مصر القديمة', 'Old Cairo'],
    ['shubra', 'شبرا', 'Shubra'],
    ['rod-el-farag', 'روض الفرج', 'Rod El Farag'],
    ['sahel', 'الساحل', 'El Sahel'],
    ['ain-shams', 'عين شمس', 'Ain Shams'],
    ['matareya', 'المطرية', 'El Matareya'],
    ['marg', 'المرج', 'El Marg'],
    ['salam-city', 'مدينة السلام', 'El Salam City'],
    ['nozha', 'النزهة', 'El Nozha'],
    ['hadayek-el-kobba', 'حدائق القبة', 'Hadayek El Kobba'],
    ['zeitoun', 'الزيتون', 'El Zeitoun'],
    ['waily', 'الوايلي', 'El Waily'],
    ['abbassia', 'العباسية', 'Abbassia'],
    ['sharabiya', 'الشرابية', 'El Sharabiya'],
    ['amiriya', 'الأميرية', 'El Amiriya'],
    ['ezbet-el-nakhl', 'عزبة النخل', 'Ezbet El Nakhl'],
    ['bulaq', 'بولاق', 'Bulaq'],
    ['mosky', 'الموسكي', 'El Mosky'],
    ['gamaleya', 'الجمالية', 'El Gamaleya'],
    ['darb-el-ahmar', 'الدرب الأحمر', 'El Darb El Ahmar'],
    ['khalifa', 'الخليفة', 'El Khalifa'],
    ['dar-el-salam', 'دار السلام', 'Dar El Salam'],
    ['basatin', 'البساتين', 'El Basatin'],
    ['manshiyat-naser', 'منشأة ناصر', 'Manshiyat Naser'],
  ]],
  ['giza', 'الجيزة', 'Giza', [
    ['dokki', 'الدقي', 'Dokki'],
    ['mohandessin', 'المهندسين', 'Mohandessin'],
    ['agouza', 'العجوزة', 'Agouza'],
    ['imbaba', 'إمبابة', 'Imbaba'],
    ['warraq', 'الوراق', 'El Warraq'],
    ['bulaq-el-dakrour', 'بولاق الدكرور', 'Bulaq El Dakrour'],
    ['faisal', 'فيصل', 'Faisal'],
    ['haram', 'الهرم', 'Haram'],
    ['omraniya', 'العمرانية', 'Omraniya'],
    ['talbia', 'الطالبية', 'Talbia'],
    ['monib', 'المنيب', 'El Monib'],
    ['hadayek-el-ahram', 'حدائق الأهرام', 'Hadayek El Ahram'],
    ['6-october', 'مدينة 6 أكتوبر', '6th of October City'],
    ['hadayek-october', 'حدائق أكتوبر', 'Hadayek October'],
    ['sheikh-zayed', 'مدينة الشيخ زايد', 'Sheikh Zayed City'],
    ['kerdasa', 'كرداسة', 'Kerdasa'],
    ['ossim', 'أوسيم', 'Ossim'],
    ['manshiyat-el-qanater', 'منشأة القناطر', 'Manshiyat El Qanater'],
    ['abu-el-nomros', 'أبو النمرس', 'Abu El Nomros'],
    ['hawamdeya', 'الحوامدية', 'El Hawamdeya'],
    ['badrashin', 'البدرشين', 'El Badrashin'],
    ['ayyat', 'العياط', 'El Ayyat'],
    ['saff', 'الصف', 'El Saff'],
    ['atfih', 'أطفيح', 'Atfih'],
    ['bahariya', 'الواحات البحرية', 'El Wahat El Bahariya'],
  ]],
  ['alexandria', 'الإسكندرية', 'Alexandria', [
    ['raml-station', 'محطة الرمل', 'Raml Station'],
    ['mansheya', 'المنشية', 'El Mansheya'],
    ['gomrok', 'الجمرك', 'El Gomrok'],
    ['bahary', 'بحري', 'Bahary'],
    ['attarin', 'العطارين', 'El Attarin'],
    ['moharam-bek', 'محرم بك', 'Moharam Bek'],
    ['karmouz', 'كرموز', 'Karmouz'],
    ['bab-sharqi', 'باب شرقي', 'Bab Sharqi'],
    ['shatby', 'الشاطبي', 'El Shatby'],
    ['camp-chezar', 'كامب شيزار', 'Camp Chezar'],
    ['ibrahimia', 'الإبراهيمية', 'El Ibrahimia'],
    ['sporting', 'سبورتنج', 'Sporting'],
    ['cleopatra', 'كليوباترا', 'Cleopatra'],
    ['sidi-gaber', 'سيدي جابر', 'Sidi Gaber'],
    ['smouha', 'سموحة', 'Smouha'],
    ['stanley', 'ستانلي', 'Stanley'],
    ['roushdy', 'رشدي', 'Roushdy'],
    ['san-stefano', 'سان ستيفانو', 'San Stefano'],
    ['gleem', 'جليم', 'Gleem'],
    ['louran', 'لوران', 'Louran'],
    ['victoria', 'فيكتوريا', 'Victoria'],
    ['sidi-bishr', 'سيدي بشر', 'Sidi Bishr'],
    ['miami', 'ميامي', 'Miami'],
    ['asafra', 'العصافرة', 'El Asafra'],
    ['mandara', 'المندرة', 'El Mandara'],
    ['montaza', 'المنتزه', 'El Montaza'],
    ['mamoura', 'المعمورة', 'El Mamoura'],
    ['abu-qir', 'أبو قير', 'Abu Qir'],
    ['mex', 'المكس', 'El Mex'],
    ['dekheila', 'الدخيلة', 'El Dekheila'],
    ['agami', 'العجمي', 'El Agami'],
    ['amreya', 'العامرية', 'El Amreya'],
    ['king-mariout', 'كينج مريوط', 'King Mariout'],
    ['borg-el-arab', 'برج العرب', 'Borg El Arab'],
    ['new-borg-el-arab', 'برج العرب الجديدة', 'New Borg El Arab'],
  ]],
  ['qalyubia', 'القليوبية', 'Qalyubia', [
    ['banha', 'بنها', 'Banha'],
    ['shubra-el-kheima', 'شبرا الخيمة', 'Shubra El Kheima'],
    ['qalyub', 'قليوب', 'Qalyub'],
    ['khanka', 'الخانكة', 'El Khanka'],
    ['khosous', 'الخصوص', 'El Khosous'],
    ['obour', 'مدينة العبور', 'El Obour City'],
    ['qanater-el-khayreya', 'القناطر الخيرية', 'El Qanater El Khayreya'],
    ['shibin-el-qanater', 'شبين القناطر', 'Shibin El Qanater'],
    ['tukh', 'طوخ', 'Tukh'],
    ['kafr-shukr', 'كفر شكر', 'Kafr Shukr'],
    ['qaha', 'قها', 'Qaha'],
  ]],
  ['sharqia', 'الشرقية', 'Sharqia', [
    ['zagazig', 'الزقازيق', 'Zagazig'],
    ['10-ramadan', 'مدينة العاشر من رمضان', '10th of Ramadan City'],
    ['belbeis', 'بلبيس', 'Belbeis'],
    ['minya-el-qamh', 'منيا القمح', 'Minya El Qamh'],
    ['abu-hammad', 'أبو حماد', 'Abu Hammad'],
    ['abu-kabir', 'أبو كبير', 'Abu Kabir'],
    ['faqous', 'فاقوس', 'Faqous'],
    ['hehya', 'ههيا', 'Hehya'],
    ['kafr-saqr', 'كفر صقر', 'Kafr Saqr'],
    ['awlad-saqr', 'أولاد صقر', 'Awlad Saqr'],
    ['husseiniya', 'الحسينية', 'El Husseiniya'],
    ['mashtoul-el-souk', 'مشتول السوق', 'Mashtoul El Souk'],
    ['ibrahimiya', 'الإبراهيمية', 'El Ibrahimiya'],
    ['diyarb-negm', 'ديرب نجم', 'Diyarb Negm'],
    ['qanayat', 'القنايات', 'El Qanayat'],
    ['san-el-hagar', 'صان الحجر', 'San El Hagar'],
  ]],
  ['dakahlia', 'الدقهلية', 'Dakahlia', [
    ['mansoura', 'المنصورة', 'Mansoura'],
    ['talkha', 'طلخا', 'Talkha'],
    ['mit-ghamr', 'ميت غمر', 'Mit Ghamr'],
    ['aga', 'أجا', 'Aga'],
    ['sinbellawein', 'السنبلاوين', 'El Sinbellawein'],
    ['dekernes', 'دكرنس', 'Dekernes'],
    ['belqas', 'بلقاس', 'Belqas'],
    ['sherbin', 'شربين', 'Sherbin'],
    ['manzala', 'المنزلة', 'El Manzala'],
    ['minyat-el-nasr', 'منية النصر', 'Minyat El Nasr'],
    ['gamasa', 'جمصة', 'Gamasa'],
    ['mit-salsil', 'ميت سلسيل', 'Mit Salsil'],
    ['matareya', 'المطرية', 'El Matareya'],
    ['tamai-el-amdid', 'تمي الأمديد', 'Tamai El Amdid'],
    ['beni-ebeid', 'بني عبيد', 'Beni Ebeid'],
    ['nabaroh', 'نبروه', 'Nabaroh'],
    ['gamaliya', 'الجمالية', 'El Gamaliya'],
  ]],
  ['gharbia', 'الغربية', 'Gharbia', [
    ['tanta', 'طنطا', 'Tanta'],
    ['mahalla', 'المحلة الكبرى', 'El Mahalla El Kubra'],
    ['kafr-el-zayat', 'كفر الزيات', 'Kafr El Zayat'],
    ['zefta', 'زفتى', 'Zefta'],
    ['samanoud', 'سمنود', 'Samanoud'],
    ['basyoun', 'بسيون', 'Basyoun'],
    ['qutur', 'قطور', 'Qutur'],
    ['santa', 'السنطة', 'El Santa'],
  ]],
  ['monufia', 'المنوفية', 'Monufia', [
    ['shebin-el-kom', 'شبين الكوم', 'Shebin El Kom'],
    ['menouf', 'منوف', 'Menouf'],
    ['sadat-city', 'مدينة السادات', 'Sadat City'],
    ['ashmoun', 'أشمون', 'Ashmoun'],
    ['quesna', 'قويسنا', 'Quesna'],
    ['berket-el-sab', 'بركة السبع', 'Berket El Sab'],
    ['tala', 'تلا', 'Tala'],
    ['bagour', 'الباجور', 'El Bagour'],
    ['shohada', 'الشهداء', 'El Shohada'],
    ['sers-el-lyan', 'سرس الليان', 'Sers El Lyan'],
  ]],
  ['beheira', 'البحيرة', 'Beheira', [
    ['damanhour', 'دمنهور', 'Damanhour'],
    ['kafr-el-dawwar', 'كفر الدوار', 'Kafr El Dawwar'],
    ['rashid', 'رشيد', 'Rashid'],
    ['edku', 'إدكو', 'Edku'],
    ['abu-el-matamir', 'أبو المطامير', 'Abu El Matamir'],
    ['abu-hummus', 'أبو حمص', 'Abu Hummus'],
    ['kom-hamada', 'كوم حمادة', 'Kom Hamada'],
    ['delengat', 'الدلنجات', 'El Delengat'],
    ['itay-el-barud', 'إيتاي البارود', 'Itay El Barud'],
    ['shubrakhit', 'شبراخيت', 'Shubrakhit'],
    ['hosh-eissa', 'حوش عيسى', 'Hosh Eissa'],
    ['mahmudiyah', 'المحمودية', 'El Mahmudiyah'],
    ['rahmaniya', 'الرحمانية', 'El Rahmaniya'],
    ['wadi-el-natrun', 'وادي النطرون', 'Wadi El Natrun'],
    ['badr', 'بدر', 'Badr'],
    ['nubaria', 'النوبارية', 'El Nubaria'],
  ]],
  ['kafr-el-sheikh', 'كفر الشيخ', 'Kafr El Sheikh', [
    ['kafr-el-sheikh', 'كفر الشيخ', 'Kafr El Sheikh'],
    ['desouk', 'دسوق', 'Desouk'],
    ['fuwwah', 'فوه', 'Fuwwah'],
    ['metoubes', 'مطوبس', 'Metoubes'],
    ['baltim', 'بلطيم', 'Baltim'],
    ['burullus', 'البرلس', 'El Burullus'],
    ['sidi-salem', 'سيدي سالم', 'Sidi Salem'],
    ['qallin', 'قلين', 'Qallin'],
    ['hamool', 'الحامول', 'El Hamool'],
    ['biyala', 'بيلا', 'Biyala'],
    ['reyad', 'الرياض', 'El Reyad'],
  ]],
  ['damietta', 'دمياط', 'Damietta', [
    ['damietta', 'دمياط', 'Damietta'],
    ['new-damietta', 'دمياط الجديدة', 'New Damietta'],
    ['ras-el-bar', 'رأس البر', 'Ras El Bar'],
    ['faraskur', 'فارسكور', 'Faraskur'],
    ['kafr-saad', 'كفر سعد', 'Kafr Saad'],
    ['zarqa', 'الزرقا', 'El Zarqa'],
    ['kafr-el-battikh', 'كفر البطيخ', 'Kafr El Battikh'],
    ['ezbet-el-borg', 'عزبة البرج', 'Ezbet El Borg'],
  ]],
  ['port-said', 'بورسعيد', 'Port Said', [
    ['port-said', 'بورسعيد', 'Port Said'],
    ['port-fouad', 'بورفؤاد', 'Port Fouad'],
    ['zohour', 'الزهور', 'El Zohour'],
    ['dawahy', 'الضواحي', 'El Dawahy'],
    ['arab', 'العرب', 'El Arab'],
    ['sharq', 'الشرق', 'El Sharq'],
    ['manakh', 'المناخ', 'El Manakh'],
    ['ganoub', 'الجنوب', 'El Ganoub'],
  ]],
  ['ismailia', 'الإسماعيلية', 'Ismailia', [
    ['ismailia', 'الإسماعيلية', 'Ismailia'],
    ['fayed', 'فايد', 'Fayed'],
    ['qantara-sharq', 'القنطرة شرق', 'El Qantara Sharq'],
    ['qantara-gharb', 'القنطرة غرب', 'El Qantara Gharb'],
    ['tal-el-kebir', 'التل الكبير', 'El Tal El Kebir'],
    ['abu-suwir', 'أبو صوير', 'Abu Suwir'],
    ['qassasin', 'القصاصين', 'El Qassasin'],
  ]],
  ['suez', 'السويس', 'Suez', [
    ['suez', 'السويس', 'Suez'],
    ['arbaeen', 'الأربعين', 'El Arbaeen'],
    ['ganayen', 'الجناين', 'El Ganayen'],
    ['ataqah', 'عتاقة', 'Ataqah'],
    ['faisal', 'فيصل', 'Faisal'],
    ['ain-sokhna', 'العين السخنة', 'Ain Sokhna'],
  ]],
  ['faiyum', 'الفيوم', 'Faiyum', [
    ['faiyum', 'الفيوم', 'Faiyum'],
    ['new-faiyum', 'الفيوم الجديدة', 'New Faiyum'],
    ['sinnuris', 'سنورس', 'Sinnuris'],
    ['tamiya', 'طامية', 'Tamiya'],
    ['itsa', 'إطسا', 'Itsa'],
    ['ibshaway', 'إبشواي', 'Ibshaway'],
    ['yousef-el-seddik', 'يوسف الصديق', 'Yousef El Seddik'],
  ]],
  ['beni-suef', 'بني سويف', 'Beni Suef', [
    ['beni-suef', 'بني سويف', 'Beni Suef'],
    ['new-beni-suef', 'بني سويف الجديدة', 'New Beni Suef'],
    ['wasta', 'الواسطى', 'El Wasta'],
    ['nasser', 'ناصر', 'Nasser'],
    ['ihnasya', 'إهناسيا', 'Ihnasya'],
    ['beba', 'ببا', 'Beba'],
    ['somasta', 'سمسطا', 'Somasta'],
    ['fashn', 'الفشن', 'El Fashn'],
  ]],
  ['minya', 'المنيا', 'Minya', [
    ['minya', 'المنيا', 'Minya'],
    ['new-minya', 'المنيا الجديدة', 'New Minya'],
    ['mallawi', 'ملوي', 'Mallawi'],
    ['samalut', 'سمالوط', 'Samalut'],
    ['matai', 'مطاي', 'Matai'],
    ['beni-mazar', 'بني مزار', 'Beni Mazar'],
    ['maghagha', 'مغاغة', 'Maghagha'],
    ['abu-qurqas', 'أبو قرقاص', 'Abu Qurqas'],
    ['deir-mawas', 'دير مواس', 'Deir Mawas'],
    ['idwa', 'العدوة', 'El Idwa'],
  ]],
  ['asyut', 'أسيوط', 'Asyut', [
    ['asyut', 'أسيوط', 'Asyut'],
    ['new-asyut', 'أسيوط الجديدة', 'New Asyut'],
    ['dairut', 'ديروط', 'Dairut'],
    ['manfalut', 'منفلوط', 'Manfalut'],
    ['qusiya', 'القوصية', 'El Qusiya'],
    ['abnub', 'أبنوب', 'Abnub'],
    ['abu-tig', 'أبو تيج', 'Abu Tig'],
    ['ghanayem', 'الغنايم', 'El Ghanayem'],
    ['sahel-selim', 'ساحل سليم', 'Sahel Selim'],
    ['badari', 'البداري', 'El Badari'],
    ['sidfa', 'صدفا', 'Sidfa'],
    ['fateh', 'الفتح', 'El Fateh'],
  ]],
  ['sohag', 'سوهاج', 'Sohag', [
    ['sohag', 'سوهاج', 'Sohag'],
    ['new-sohag', 'سوهاج الجديدة', 'New Sohag'],
    ['akhmim', 'أخميم', 'Akhmim'],
    ['girga', 'جرجا', 'Girga'],
    ['tahta', 'طهطا', 'Tahta'],
    ['tama', 'طما', 'Tama'],
    ['maragha', 'المراغة', 'El Maragha'],
    ['balyana', 'البلينا', 'El Balyana'],
    ['dar-el-salam', 'دار السلام', 'Dar El Salam'],
    ['juhayna', 'جهينة', 'Juhayna'],
    ['monshah', 'المنشاة', 'El Monshah'],
    ['saqultah', 'ساقلتة', 'Saqultah'],
    ['usayrat', 'العسيرات', 'El Usayrat'],
  ]],
  ['qena', 'قنا', 'Qena', [
    ['qena', 'قنا', 'Qena'],
    ['new-qena', 'قنا الجديدة', 'New Qena'],
    ['nag-hammadi', 'نجع حمادي', 'Nag Hammadi'],
    ['qus', 'قوص', 'Qus'],
    ['dishna', 'دشنا', 'Dishna'],
    ['abu-tesht', 'أبو تشت', 'Abu Tesht'],
    ['farshut', 'فرشوط', 'Farshut'],
    ['naqada', 'نقادة', 'Naqada'],
    ['qift', 'قفط', 'Qift'],
    ['waqf', 'الوقف', 'El Waqf'],
  ]],
  ['luxor', 'الأقصر', 'Luxor', [
    ['luxor', 'الأقصر', 'Luxor'],
    ['esna', 'إسنا', 'Esna'],
    ['armant', 'أرمنت', 'Armant'],
    ['qurna', 'القرنة', 'El Qurna'],
    ['bayadiya', 'البياضية', 'El Bayadiya'],
    ['tod', 'الطود', 'El Tod'],
    ['zeiniya', 'الزينية', 'El Zeiniya'],
  ]],
  ['aswan', 'أسوان', 'Aswan', [
    ['aswan', 'أسوان', 'Aswan'],
    ['new-aswan', 'أسوان الجديدة', 'New Aswan'],
    ['kom-ombo', 'كوم أمبو', 'Kom Ombo'],
    ['edfu', 'إدفو', 'Edfu'],
    ['daraw', 'دراو', 'Daraw'],
    ['nasr-el-nuba', 'نصر النوبة', 'Nasr El Nuba'],
    ['kalabsha', 'كلابشة', 'Kalabsha'],
    ['abu-simbel', 'أبو سمبل', 'Abu Simbel'],
  ]],
  ['red-sea', 'البحر الأحمر', 'Red Sea', [
    ['hurghada', 'الغردقة', 'Hurghada'],
    ['el-gouna', 'الجونة', 'El Gouna'],
    ['sahl-hasheesh', 'سهل حشيش', 'Sahl Hasheesh'],
    ['safaga', 'سفاجا', 'Safaga'],
    ['quseir', 'القصير', 'El Quseir'],
    ['marsa-alam', 'مرسى علم', 'Marsa Alam'],
    ['ras-gharib', 'رأس غارب', 'Ras Gharib'],
    ['shalateen', 'الشلاتين', 'El Shalateen'],
    ['halaib', 'حلايب', 'Halaib'],
  ]],
  ['new-valley', 'الوادي الجديد', 'New Valley', [
    ['kharga', 'الخارجة', 'El Kharga'],
    ['dakhla', 'الداخلة', 'El Dakhla'],
    ['farafra', 'الفرافرة', 'El Farafra'],
    ['paris', 'باريس', 'Paris'],
    ['balat', 'بلاط', 'Balat'],
  ]],
  ['matrouh', 'مطروح', 'Matrouh', [
    ['marsa-matrouh', 'مرسى مطروح', 'Marsa Matrouh'],
    ['hammam', 'الحمام', 'El Hammam'],
    ['negaila', 'النجيلة', 'El Negaila'],
    ['sidi-barrani', 'سيدي براني', 'Sidi Barrani'],
    ['sallum', 'السلوم', 'El Sallum'],
    ['siwa', 'سيوة', 'Siwa'],
  ]],
  ['north-sinai', 'شمال سيناء', 'North Sinai', [
    ['arish', 'العريش', 'El Arish'],
    ['bir-el-abd', 'بئر العبد', 'Bir El Abd'],
    ['sheikh-zuweid', 'الشيخ زويد', 'Sheikh Zuweid'],
    ['rafah', 'رفح', 'Rafah'],
    ['hasana', 'الحسنة', 'El Hasana'],
    ['nakhl', 'نخل', 'Nakhl'],
  ]],
  ['south-sinai', 'جنوب سيناء', 'South Sinai', [
    ['sharm-el-sheikh', 'شرم الشيخ', 'Sharm El Sheikh'],
    ['dahab', 'دهب', 'Dahab'],
    ['nuweiba', 'نويبع', 'Nuweiba'],
    ['taba', 'طابا', 'Taba'],
    ['el-tor', 'الطور', 'El Tor'],
    ['saint-catherine', 'سانت كاترين', 'Saint Catherine'],
    ['ras-sedr', 'رأس سدر', 'Ras Sedr'],
    ['abu-rudeis', 'أبو رديس', 'Abu Rudeis'],
    ['abu-zenima', 'أبو زنيمة', 'Abu Zenima'],
  ]],
  // Not a governorate: the coast merchants price on its own (EasyOrders does
  // the same). Its towns belong to Alexandria and Matrouh on a courier's list.
  ['north-coast', 'الساحل الشمالي', 'North Coast', [
    ['sidi-kerir', 'سيدي كرير', 'Sidi Kerir'],
    ['marina', 'مارينا', 'Marina'],
    ['el-alamein', 'العلمين', 'El Alamein'],
    ['new-alamein', 'العلمين الجديدة', 'New Alamein'],
    ['sidi-abdel-rahman', 'سيدي عبد الرحمن', 'Sidi Abdel Rahman'],
    ['dabaa', 'الضبعة', 'El Dabaa'],
    ['ras-el-hekma', 'رأس الحكمة', 'Ras El Hekma'],
  ]],
];

const SAUDI = [
  ['riyadh', 'منطقة الرياض', 'Riyadh Region', [
    ['riyadh', 'الرياض', 'Riyadh'],
    ['al-kharj', 'الخرج', 'Al Kharj'],
    ['diriyah', 'الدرعية', 'Diriyah'],
    ['al-majmaah', 'المجمعة', 'Al Majmaah'],
    ['az-zulfi', 'الزلفي', 'Az Zulfi'],
    ['shaqra', 'شقراء', 'Shaqra'],
    ['ad-dawadmi', 'الدوادمي', 'Ad Dawadmi'],
    ['wadi-ad-dawasir', 'وادي الدواسر', 'Wadi Ad Dawasir'],
    ['al-aflaj', 'الأفلاج', 'Al Aflaj'],
    ['al-quwayiyah', 'القويعية', 'Al Quwayiyah'],
  ]],
  ['makkah', 'منطقة مكة المكرمة', 'Makkah Region', [
    ['makkah', 'مكة المكرمة', 'Makkah'],
    ['jeddah', 'جدة', 'Jeddah'],
    ['taif', 'الطائف', 'Taif'],
    ['rabigh', 'رابغ', 'Rabigh'],
    ['al-qunfudhah', 'القنفذة', 'Al Qunfudhah'],
    ['al-lith', 'الليث', 'Al Lith'],
    ['al-jumum', 'الجموم', 'Al Jumum'],
    ['khulais', 'خليص', 'Khulais'],
  ]],
  ['madinah', 'منطقة المدينة المنورة', 'Madinah Region', [
    ['madinah', 'المدينة المنورة', 'Madinah'],
    ['yanbu', 'ينبع', 'Yanbu'],
    ['al-ula', 'العلا', 'Al Ula'],
    ['badr', 'بدر', 'Badr'],
    ['khaybar', 'خيبر', 'Khaybar'],
    ['al-hinakiyah', 'الحناكية', 'Al Hinakiyah'],
    ['mahd-adh-dhahab', 'مهد الذهب', 'Mahd Adh Dhahab'],
  ]],
  ['eastern', 'المنطقة الشرقية', 'Eastern Province', [
    ['dammam', 'الدمام', 'Dammam'],
    ['al-khobar', 'الخبر', 'Al Khobar'],
    ['dhahran', 'الظهران', 'Dhahran'],
    ['al-ahsa', 'الأحساء', 'Al Ahsa'],
    ['al-jubail', 'الجبيل', 'Al Jubail'],
    ['qatif', 'القطيف', 'Qatif'],
    ['hafar-al-batin', 'حفر الباطن', 'Hafar Al Batin'],
    ['al-khafji', 'الخفجي', 'Al Khafji'],
    ['ras-tanura', 'رأس تنورة', 'Ras Tanura'],
    ['abqaiq', 'بقيق', 'Abqaiq'],
    ['al-nairyah', 'النعيرية', 'Al Nairyah'],
  ]],
  ['qassim', 'منطقة القصيم', 'Al Qassim Region', [
    ['buraydah', 'بريدة', 'Buraydah'],
    ['unaizah', 'عنيزة', 'Unaizah'],
    ['ar-rass', 'الرس', 'Ar Rass'],
    ['al-mithnab', 'المذنب', 'Al Mithnab'],
    ['al-bukayriyah', 'البكيرية', 'Al Bukayriyah'],
    ['al-badai', 'البدائع', 'Al Badai'],
  ]],
  ['asir', 'منطقة عسير', 'Asir Region', [
    ['abha', 'أبها', 'Abha'],
    ['khamis-mushait', 'خميس مشيط', 'Khamis Mushait'],
    ['bisha', 'بيشة', 'Bisha'],
    ['muhayil', 'محايل عسير', 'Muhayil'],
    ['an-namas', 'النماص', 'An Namas'],
    ['ahad-rafidah', 'أحد رفيدة', 'Ahad Rafidah'],
    ['sarat-abidah', 'سراة عبيدة', 'Sarat Abidah'],
  ]],
  ['tabuk', 'منطقة تبوك', 'Tabuk Region', [
    ['tabuk', 'تبوك', 'Tabuk'],
    ['duba', 'ضباء', 'Duba'],
    ['al-wajh', 'الوجه', 'Al Wajh'],
    ['umluj', 'أملج', 'Umluj'],
    ['tayma', 'تيماء', 'Tayma'],
    ['haql', 'حقل', 'Haql'],
  ]],
  ['hail', 'منطقة حائل', 'Hail Region', [
    ['hail', 'حائل', 'Hail'],
    ['baqaa', 'بقعاء', 'Baqaa'],
    ['al-ghazalah', 'الغزالة', 'Al Ghazalah'],
    ['ash-shinan', 'الشنان', 'Ash Shinan'],
  ]],
  ['northern-borders', 'منطقة الحدود الشمالية', 'Northern Borders Region', [
    ['arar', 'عرعر', 'Arar'],
    ['rafha', 'رفحاء', 'Rafha'],
    ['turaif', 'طريف', 'Turaif'],
    ['al-uwayqilah', 'العويقيلة', 'Al Uwayqilah'],
  ]],
  ['jazan', 'منطقة جازان', 'Jazan Region', [
    ['jazan', 'جازان', 'Jazan'],
    ['sabya', 'صبيا', 'Sabya'],
    ['abu-arish', 'أبو عريش', 'Abu Arish'],
    ['samtah', 'صامطة', 'Samtah'],
    ['baish', 'بيش', 'Baish'],
    ['ad-darb', 'الدرب', 'Ad Darb'],
    ['farasan', 'فرسان', 'Farasan'],
  ]],
  ['najran', 'منطقة نجران', 'Najran Region', [
    ['najran', 'نجران', 'Najran'],
    ['sharurah', 'شرورة', 'Sharurah'],
    ['hubuna', 'حبونا', 'Hubuna'],
    ['yadamah', 'يدمة', 'Yadamah'],
  ]],
  ['al-bahah', 'منطقة الباحة', 'Al Bahah Region', [
    ['al-bahah', 'الباحة', 'Al Bahah'],
    ['baljurashi', 'بلجرشي', 'Baljurashi'],
    ['al-mandaq', 'المندق', 'Al Mandaq'],
    ['al-mikhwah', 'المخواة', 'Al Mikhwah'],
    ['al-aqiq', 'العقيق', 'Al Aqiq'],
    ['qilwah', 'قلوة', 'Qilwah'],
  ]],
  ['al-jouf', 'منطقة الجوف', 'Al Jouf Region', [
    ['sakaka', 'سكاكا', 'Sakaka'],
    ['dumat-al-jandal', 'دومة الجندل', 'Dumat Al Jandal'],
    ['al-qurayyat', 'القريات', 'Al Qurayyat'],
    ['tabarjal', 'طبرجل', 'Tabarjal'],
  ]],
];

/** The rows of geo_regions, parents first, in display order. */
function rows() {
  const out = [];
  const add = (country, prefix, list) => {
    list.forEach(([slug, ar, en, cities], i) => {
      const code = `${prefix}${slug}`;
      out.push({ code, country, level: 'governorate', parentCode: null, nameAr: ar, nameEn: en, sortOrder: i });
      cities.forEach(([citySlug, cityAr, cityEn], j) => {
        out.push({ code: `${code}.${citySlug}`, country, level: 'city', parentCode: code, nameAr: cityAr, nameEn: cityEn, sortOrder: j });
      });
    });
  };
  add('EG', '', EGYPT);
  add('SA', 'sa-', SAUDI);
  return out;
}

module.exports = { rows };
