'use strict';

/**
 * Names nobody may take as a username: the platform's own words, the store
 * subdomains we keep (core/utils/workspaceSlug RESERVED_SLUGS), and the routes
 * of the dashboard, the storefront and the platform console — anything that
 * could pass for an official account or collide with a path. One list; the
 * username rules (users/username.js) and the backfill (migration 124) read it.
 * Compared after lower-casing.
 */
const RESERVED_USERNAMES = Object.freeze([
  // Platform and staff
  'admin',
  'administrator',
  'admins',
  'root',
  'system',
  'sysadmin',
  'superuser',
  'support',
  'help',
  'helpdesk',
  'billing',
  'zimos',
  'zimos.support',
  'zimos_support',
  'official',
  'staff',
  'team',
  'moderator',
  'owner',
  'creator',
  'agent',
  'security',
  'abuse',
  'postmaster',
  'webmaster',
  'hostmaster',
  'noreply',
  'no_reply',
  'no.reply',
  'mail',
  'email',
  'info',
  'contact',
  'null',
  'undefined',
  'none',
  'anonymous',
  // Store subdomains we keep (workspaceSlug RESERVED_SLUGS)
  'www',
  'api',
  'app',
  'store',
  'ftp',
  'cdn',
  'ns1',
  'ns2',
  'blog',
  'status',
  'staging',
  'dev',
  'test',
  // Dashboard, auth and console routes
  'login',
  'logout',
  'register',
  'signup',
  'signin',
  'auth',
  'oauth',
  'google',
  'verify',
  'reset',
  'password',
  'account',
  'settings',
  'profile',
  'me',
  'dashboard',
  'overview',
  'workspaces',
  'catalog',
  'collections',
  'confirmation',
  'confirmation_queue',
  'funnels',
  'website',
  'analytics',
  'customers',
  'payments',
  'returns',
  'reviews',
  'discounts',
  'shipping',
  'invoices',
  'plans',
  'subscriptions',
  'templates',
  'platform',
  'console',
  // Storefront routes (pagesService RESERVED_PAGE_SEGMENTS) and pages
  'cart',
  'checkout',
  'products',
  'orders',
  'offer',
  'track',
  'preview',
  'pay',
  'about',
  'terms',
  'privacy',
  'legal',
]);

const RESERVED = new Set(RESERVED_USERNAMES);

const isReservedUsername = (value) => RESERVED.has(String(value || '').toLowerCase());

module.exports = { RESERVED_USERNAMES, isReservedUsername };
